-- =====================================================================
-- reset_sequences.sql
--
-- Se ejecuta DESPUÉS de la carga de datos con pgloader y de aplicar las
-- constraints (post_migration_constraints.sql).
--
-- PROBLEMA QUE RESUELVE
-- En AdventureWorks (SQL Server) varias primary keys son columnas
-- IDENTITY: DepartmentID, ShiftID, JobCandidateID y BusinessEntityID.
-- pgloader copia los valores pero NO traslada la propiedad de
-- autogeneración: las columnas quedan como enteros normales, sin
-- secuencia ni identity. El resultado es que cualquier INSERT que no
-- especifique la primary key falla con "null value in column ...
-- violates not-null constraint", lo que impide crear registros desde la
-- aplicación.
--
-- La opción `reset sequences` de pgloader tampoco ayuda, porque no hay
-- secuencias que reajustar.
--
-- QUÉ HACE ESTE SCRIPT
--   1. Detecta las tablas de `humanresources` y `person` cuya primary
--      key es una sola columna entera que NO es a la vez foreign key
--      (esas son las verdaderas columnas autogeneradas: department,
--      shift, jobcandidate, businessentity; quedan excluidas employee y
--      person, cuya PK es además FK hacia otra tabla).
--   2. Si a la columna le falta la identity, se la añade como GENERATED
--      BY DEFAULT (no ALWAYS, para no romper cargas que sí traen id
--      explícito), arrancando en MAX(id) + 1.
--   3. Si ya tenía secuencia, la reajusta a MAX(id).
--   4. Verifica con un INSERT de prueba por tabla, usando DEFAULT en la
--      columna autogenerada y valores dummy en el resto de columnas
--      NOT NULL sin default.
--   5. Elimina cada registro de prueba, sin dejar rastro.
--
-- Es idempotente: se puede ejecutar tantas veces como sea necesario,
-- antes o después de tener datos reales en las tablas.
-- =====================================================================

DO $$
DECLARE
    tbl RECORD;
    seq_name text;
    max_id bigint;
    other_col RECORD;
    insert_cols text;
    insert_vals text;
    dummy_val text;
    new_id bigint;
    tablas_procesadas int := 0;
BEGIN
    FOR tbl IN
        SELECT
            n.nspname       AS schema_name,
            c.relname       AS table_name,
            a.attname       AS pk_column,
            a.attidentity   AS identity_kind
        FROM pg_constraint con
        JOIN pg_class c ON c.oid = con.conrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        JOIN pg_attribute a
            ON a.attrelid = c.oid AND a.attnum = con.conkey[1]
        WHERE con.contype = 'p'
          AND array_length(con.conkey, 1) = 1
          AND n.nspname IN ('humanresources', 'person')
          -- Solo columnas enteras: son las candidatas a autogenerarse.
          AND a.atttypid IN ('int2'::regtype, 'int4'::regtype, 'int8'::regtype)
          -- Excluye las PK que además son FK (employee, person): su valor
          -- viene de la tabla padre, no se autogenera.
          AND NOT EXISTS (
              SELECT 1
              FROM pg_constraint fk
              WHERE fk.conrelid = c.oid
                AND fk.contype = 'f'
                AND a.attnum = ANY (fk.conkey)
          )
        ORDER BY n.nspname, c.relname
    LOOP
        BEGIN
            EXECUTE format(
                'SELECT max(%I) FROM %I.%I',
                tbl.pk_column, tbl.schema_name, tbl.table_name
            ) INTO max_id;

            seq_name := pg_get_serial_sequence(
                tbl.schema_name || '.' || tbl.table_name, tbl.pk_column
            );

            IF tbl.identity_kind = '' AND seq_name IS NULL THEN
                -- 1. Falta la autogeneración: crearla arrancando en max + 1.
                EXECUTE format(
                    'ALTER TABLE %I.%I ALTER COLUMN %I '
                    'ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                    tbl.schema_name, tbl.table_name, tbl.pk_column,
                    COALESCE(max_id, 0) + 1
                );

                RAISE NOTICE 'Identity creada en %.%.% (arranca en %)',
                    tbl.schema_name, tbl.table_name, tbl.pk_column,
                    COALESCE(max_id, 0) + 1;
            ELSE
                -- 2. Ya existe: solo reajustar al máximo id migrado.
                seq_name := pg_get_serial_sequence(
                    tbl.schema_name || '.' || tbl.table_name, tbl.pk_column
                );

                IF max_id IS NULL THEN
                    PERFORM setval(seq_name, 1, false);
                ELSE
                    PERFORM setval(seq_name, max_id, true);
                END IF;

                RAISE NOTICE 'Secuencia % reajustada (max id = %)',
                    seq_name, COALESCE(max_id, 0);
            END IF;

            -- 3. Armar un INSERT de prueba: DEFAULT en la columna
            --    autogenerada + valores dummy en columnas NOT NULL sin
            --    default, según su tipo de dato.
            insert_cols := '';
            insert_vals := '';

            FOR other_col IN
                SELECT
                    a.attname AS column_name,
                    format_type(a.atttypid, a.atttypmod) AS data_type
                FROM pg_attribute a
                JOIN pg_class c ON c.oid = a.attrelid
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = tbl.schema_name
                  AND c.relname = tbl.table_name
                  AND a.attnum > 0
                  AND NOT a.attisdropped
                  AND a.attname <> tbl.pk_column
                  AND a.attnotnull
                  AND NOT EXISTS (
                      SELECT 1 FROM pg_attrdef d
                      WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum
                  )
            LOOP
                dummy_val := CASE
                    WHEN other_col.data_type ILIKE 'character varying%'
                      OR other_col.data_type ILIKE 'character(%'
                      OR other_col.data_type = 'text'
                        THEN quote_literal('seq_test')
                    WHEN other_col.data_type ILIKE 'numeric%'
                      OR other_col.data_type IN
                          ('integer', 'smallint', 'bigint', 'real',
                           'double precision', 'money')
                        THEN '0'
                    WHEN other_col.data_type = 'boolean'
                        THEN 'false'
                    WHEN other_col.data_type ILIKE 'timestamp%'
                      OR other_col.data_type = 'date'
                        THEN 'now()'
                    WHEN other_col.data_type ILIKE 'time%'
                        THEN quote_literal('00:00:00')
                    WHEN other_col.data_type = 'uuid'
                        THEN 'gen_random_uuid()'
                    ELSE 'NULL'
                END;

                insert_cols := insert_cols || quote_ident(other_col.column_name) || ', ';
                insert_vals := insert_vals || dummy_val || ', ';
            END LOOP;

            IF insert_cols <> '' THEN
                insert_cols := left(insert_cols, length(insert_cols) - 2);
                insert_vals := left(insert_vals, length(insert_vals) - 2);
            END IF;

            -- 4. Insertar el registro de prueba
            IF insert_cols = '' THEN
                EXECUTE format(
                    'INSERT INTO %I.%I DEFAULT VALUES RETURNING %I',
                    tbl.schema_name, tbl.table_name, tbl.pk_column
                ) INTO new_id;
            ELSE
                EXECUTE format(
                    'INSERT INTO %I.%I (%s) VALUES (%s) RETURNING %I',
                    tbl.schema_name, tbl.table_name,
                    insert_cols, insert_vals, tbl.pk_column
                ) INTO new_id;
            END IF;

            RAISE NOTICE 'Inserción de prueba en %.% exitosa (id = %)',
                tbl.schema_name, tbl.table_name, new_id;

            -- 5. Eliminar el registro de prueba
            EXECUTE format(
                'DELETE FROM %I.%I WHERE %I = %L',
                tbl.schema_name, tbl.table_name, tbl.pk_column, new_id
            );

            RAISE NOTICE 'Registro de prueba eliminado de %.%',
                tbl.schema_name, tbl.table_name;

            tablas_procesadas := tablas_procesadas + 1;
        EXCEPTION WHEN OTHERS THEN
            RAISE WARNING 'Falló el ajuste/verificación de %.%: %',
                tbl.schema_name, tbl.table_name, SQLERRM;
        END;
    END LOOP;

    RAISE NOTICE 'Ajuste de autogeneración completo. Tablas procesadas: %',
        tablas_procesadas;
END $$;
